// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDls1ZmpPt2FyMay0SXP50WY2-MsK2Iolc',
    appId: '1:251462702127:web:d83324bd8643a3c2c2e2da',
    messagingSenderId: '251462702127',
    projectId: 'apni-dukan-62500',
    authDomain: 'apni-dukan-62500.firebaseapp.com',
    storageBucket: 'apni-dukan-62500.appspot.com',
    measurementId: 'G-0DKGDV9S6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCnwdkwQS23UhIIRmn7BxoNXURbThtgmQ',
    appId: '1:251462702127:android:59158cf47fe69435c2e2da',
    messagingSenderId: '251462702127',
    projectId: 'apni-dukan-62500',
    storageBucket: 'apni-dukan-62500.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC-NlwnGN0ssqAoMphwwQ4irVccXJ8_es',
    appId: '1:251462702127:ios:6b88e3044a819a6ac2e2da',
    messagingSenderId: '251462702127',
    projectId: 'apni-dukan-62500',
    storageBucket: 'apni-dukan-62500.appspot.com',
    iosBundleId: 'com.example.blocDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC-NlwnGN0ssqAoMphwwQ4irVccXJ8_es',
    appId: '1:251462702127:ios:7ce786f305e3136fc2e2da',
    messagingSenderId: '251462702127',
    projectId: 'apni-dukan-62500',
    storageBucket: 'apni-dukan-62500.appspot.com',
    iosBundleId: 'com.example.blocDemo.RunnerTests',
  );
}
